In [1]:
import numpy as np

In [3]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
np.zeros((1,3))

array([[ 0.,  0.,  0.]])

In [8]:
np.zeros((2,1))

array([[ 0.],
       [ 0.]])

In [9]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [10]:
np.linspace(0,100,10)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [11]:
np.linspace(0,100,11)

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.random.rand(5)

array([ 0.55904737,  0.7239409 ,  0.82960967,  0.82738162,  0.54184845])

In [16]:
np.random.rand(5,3)

array([[ 0.6135669 ,  0.41658409,  0.57210953],
       [ 0.36546341,  0.01053653,  0.47408333],
       [ 0.5639724 ,  0.55639494,  0.44249764],
       [ 0.35013329,  0.25062929,  0.99409954],
       [ 0.67477856,  0.15268683,  0.79142039]])

In [20]:
np.random.randn(2,3)

array([[-0.49594429, -1.31111871,  1.06992918],
       [-0.5885309 , -0.94843654, -0.44076768]])

In [23]:
np.random.randint(1,100)

63

In [24]:
np.random.randint(1,100,4)

array([79,  1, 39, 45])

In [26]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [31]:
np.array([[1,2,3],[1,3,3]])

array([[1, 2, 3],
       [1, 3, 3]])

In [38]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [41]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [42]:
np.ones((1,2))

array([[ 1.,  1.]])

In [43]:
np.linspace(3,5,6)

array([ 3. ,  3.4,  3.8,  4.2,  4.6,  5. ])

In [45]:
np.linspace(0,100,11)

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

In [46]:
np.eye(8)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [48]:
np.random.rand(5)

array([ 0.5509562 ,  0.24626611,  0.70116552,  0.72852413,  0.03856734])

In [49]:
np.random.rand(5,5)

array([[ 0.06396077,  0.91018159,  0.0519624 ,  0.63209156,  0.97796851],
       [ 0.75031275,  0.93964828,  0.62175082,  0.39534935,  0.73990799],
       [ 0.75658266,  0.75695917,  0.20080659,  0.19050956,  0.93104082],
       [ 0.46237922,  0.26629216,  0.33936976,  0.50310941,  0.72413221],
       [ 0.90120731,  0.96692726,  0.75358507,  0.3483174 ,  0.53531101]])

In [50]:
np.random.randn(3,4)

array([[ 0.47526422,  0.27210315,  0.99013466,  2.200323  ],
       [ 0.36314615,  2.34826709,  0.67596532,  0.29764599],
       [ 1.0211066 ,  2.15723612, -1.63970617, -1.26482071]])

In [53]:
np.random.randn(1)

array([-1.74056447])

In [55]:
np.random.randn(5,10)

array([[-1.89199947,  1.78884621, -1.18820834,  0.68946578,  0.62679526,
        -0.58401525,  0.02342669,  0.50929012,  0.12045998, -0.64825502],
       [ 1.21346456, -1.13783482, -0.27386916,  1.35869587, -0.20101825,
        -1.85760044,  1.32737765,  0.76385558,  1.50356684, -0.20512849],
       [-0.19463304,  2.06572945,  0.41339443,  1.35526186,  0.40515065,
         2.53500047, -0.43547585, -1.07079744, -0.41354311, -0.12004834],
       [-0.27105215, -1.17760857, -0.70191421,  1.35410739,  0.33390551,
         0.11013468, -0.92101572, -0.67649545, -1.17549965, -0.01650037],
       [ 0.10013231,  0.13084011, -0.30236078,  0.19674044,  0.22052873,
         0.59654617, -0.19001964,  0.79811275, -1.28014579,  0.08090566]])

In [56]:
randarr = np.random.randint(0,50,10)

In [57]:
randarr

array([31, 33, 36, 40, 19, 31, 23, 36, 25, 30])

In [58]:
randarr.reshape(2,5)

array([[31, 33, 36, 40, 19],
       [31, 23, 36, 25, 30]])

In [59]:
randarr.max()

40

In [60]:
randarr.argmax()

3

In [65]:
randarr.shape

(2, 5)

In [64]:
randarr = randarr.reshape(2,5)

In [66]:
import numpy.random as rand

In [71]:
rand.randint(0,2)

1

# Numpy array indexing

In [76]:
array = np.arange(0,30)

In [77]:
array[:4]

array([0, 1, 2, 3])

In [78]:
array[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

In [79]:
array[:5] = 50

In [80]:
array

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
slice_of_arr=array[:5]

In [82]:
slice_of_arr[:] = 50

In [83]:
slice_of_arr

array([50, 50, 50, 50, 50])

In [84]:
array

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Note that changing the slice changes the original array!!!

In [85]:
array_copy = array.copy()

In [86]:
array_copy

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [87]:
array_copy[:]=66

In [88]:
array_copy

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66,
       66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66])

In [89]:
array

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [94]:
array_copy = array.copy()

In [91]:
array_copy

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [116]:
array2d = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,5]])

In [117]:
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 5]])

In [118]:
array2d[1][1]

2

In [119]:
array2d[:2,1:]

array([[2, 3, 4],
       [2, 3, 4]])

In [120]:
type(array2d)

numpy.ndarray

In [121]:
array2d > 3

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]], dtype=bool)

In [158]:
array1  = np.arange(0,5)

In [159]:
array1

array([0, 1, 2, 3, 4])

In [160]:
bool_array = array1<2

In [155]:
bool_array

array([ True,  True, False, False, False], dtype=bool)

In [163]:
array1[array1>2]

array([3, 4])

In [166]:
array2d=np.arange(0,50).reshape(5,10)

In [167]:
array2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [169]:
array2d[1:3,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

# NumpPy operations

In [171]:
array = np.arange(0,11)

In [172]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [174]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [175]:
1/0

ZeroDivisionError: division by zero

In [176]:
array /array

/home/casper/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [177]:
 array / 1

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [178]:
1/array

/home/casper/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [179]:
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [180]:
np.exp(array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [181]:
np.max(array)

10

In [186]:
np.negative(array)

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])